version: '3.8'

networks:
  hadnetwork:

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    networks:
      - hadnetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pingpongBackend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    networks:
      - hadnetwork
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pingpongFrontend
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - db
      - backend
    networks:
      - hadnetwork

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
      - backend
    env_file:
      - .env
    ports:
      - 5050:80
    networks:
      - hadnetwork