version: '3.8'

volumes:
  db_volume:
    driver: local
    name: db_volume
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/database
      # device: $HOME/data/database
      # device: $HOME/goinfre/data/database
      # device: /home/mbadaoui/data/database
  backend_volume:
    driver: local
    name: backend_volume
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/backend
      # device: $HOME/data/backend
      # device: $HOME/goinfre/data/backend
      # device: /home/mbadaoui/data/backend
  frontend_volume:
    driver: local
    name: frontend_volume
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/frontend
      # device: $HOME/goinfre/data/frontend
      # device: $HOME/data/frontend

networks:
  hadnetwork:

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    networks:
      - hadnetwork
    volumes:
      - db_volume:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: pingpongBackend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
    networks:
      - hadnetwork
    volumes:
      - backend_volume:/app
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: pingpongFrontend
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - db
      - backend
    networks:
      - hadnetwork
    volumes:
      - frontend_volume:/app

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
      - backend
    env_file:
      - .env
    ports:
      - 5050:80
    networks:
      - hadnetwork
    # volumes:
    #   - db_volume:/var/lib/postgresql/data

  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   restart: always
  #   environment:
  #     POSTGRES_USER: hamid
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: nest
  #   networks:
  #     - hadnetwork