FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm i

RUN npm i --save @nestjs/websockets @nestjs/platform-socket.io

COPY . .

RUN npx prisma generate

RUN npm run build

RUN npm rebuild bcrypt --update-binary
# npm run start:dev
EXPOSE 8000

ENTRYPOINT [ "sh", "script_helper.sh" ]

CMD [ "npm", "run", "start:dev" ]
