FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

RUN npm run build

RUN npm rebuild bcrypt --update-binary

RUN npx prisma generate

ENTRYPOINT [ "sh", "script_helper.sh" ]

CMD [ "npm", "run", "start" ]
