version: '3.8'

services:
  postgresql:
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: hamid
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
    networks:
      - hadnetwork

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 5432:8080  

networks:
  hadnetwork: